language: haskell
# NB: don't set `language: haskell` here

# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
env:
 - GHCVER=7.8.3

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install llvm
 - travis_retry sudo apt-get install cabal-install-1.20 ghc-$GHCVER-prof ghc-$GHCVER-dyn happy
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - sudo /opt/ghc/$GHCVER/bin/ghc-pkg recache
 - /opt/ghc/$GHCVER/bin/ghc-pkg recache --user
 - cabal-1.20 update
 - cabal-1.20 install --only-dependencies --enable-tests --enable-benchmarks

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - cabal-1.20 configure -flib-Werror --enable-tests -v2 # --ghc-options="-Werror"  # -v2 provides useful information for debugging
 - cabal-1.20 build   # this builds all libraries and executables (including tests/benchmarks)
 - cabal-1.20 test   --show-details=always
 # - cabal-1.20 check
 #- cabal-1.20 sdist   # tests that a source-distribution can be generated

# The following scriptlet checks that the resulting source distribution can be built & installed
 - function install_from_tarball {
   export SRC_TGZ=$(cabal-1.20 info . | awk '{print $2 ".tar.gz";exit}') ;
   if [ -f "dist/$SRC_TGZ" ]; then
      cabal-1.20 install "dist/$SRC_TGZ";
   else
      echo "expected 'dist/$SRC_TGZ' not found";
      exit 1;
   fi
   }
 #- install_from_tarball

